express/main/routes.py
from express.models import Post

from flask import render_template,url_for, request, Blueprint
from flask_login import  current_user

main = Blueprint('main',__name__)

@main.route("/")
@main.route("/home")
def home():
    if(current_user.is_authenticated):
        image = url_for('static',filename='images/profile_pictures/'+ current_user.image_file)
        page = request.args.get('page',default = 1,type = int)
        posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page,per_page = 5)
        return render_template('home.html' , title="Home", image = image, posts = posts, context="Home")
    else : 
        return render_template("welcome_page.html")

express/posts/routes.py
from express import db
from express.posts.forms import CreatePostForm 
from express.models import Post 

from flask import render_template,url_for, flash, redirect , request, abort, Blueprint
from flask_login import  current_user , login_required
from sqlalchemy import or_

posts = Blueprint('posts',__name__)

@posts.route("/post/create",methods=['GET','POST'])
@login_required
def create_post():
    image = url_for('static',filename='images/profile_pictures/'+ current_user.image_file)
    form = CreatePostForm()
    if(form.validate_on_submit()):
        newPost = Post(title = form.title.data,content = form.content.data, author = current_user)
        newPost.create_post()
        flash('Your post has been published!', 'success')
        return redirect(url_for('main.home'))

    return render_template("create_post.html",title = "New Post", form = form , image=image , context="create")

@posts.route("/post/edit/<int:post_id>",methods=['GET','POST'])
@login_required
def edit_post(post_id):
    image = url_for('static',filename='images/profile_pictures/'+ current_user.image_file)
    post = Post.query.get_or_404(post_id)
    if(current_user != post.author):
        abort(403)
    form = CreatePostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('main.home'))
    elif request.method == "GET" :
        form.title.data = post.title
        form.content.data = post.content
    return render_template("create_post.html",title = "Edit Post", form = form , context="edit", image = image)

@posts.route("/post/delete/<int:post_id>",methods=['GET','POST'])
@login_required
def delete_post(post_id):
    image = url_for('static',filename='images/profile_pictures/'+ current_user.image_file)
    post = Post.query.get_or_404(post_id)
    if(current_user != post.author):
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

@posts.route('/search')
def search():
    image = url_for('static',filename='images/profile_pictures/'+ current_user.image_file)
    page = request.args.get('page',default = 1,type = int)
    query = request.args.get('query', default='')
    query = f"%{query}%"
    posts = Post.query.filter(or_(Post.title.like(query), Post.content.like(query))).paginate(page=page,per_page = 5)
    return render_template('home.html' , title="Home", image = image, posts = posts,context="Search")

express/users/routes.py
from express import bcrypt,db
from express.users.forms import SignupForm,LoginForm, UpdateAccountForm, ResetPasswordForm, ResetPasswordRequestForm
from express.models import User, Post
from express.utils.profile_picture_utils import save_picture
from express.utils.email_utils import send_reset_password_email

from flask import render_template,url_for, flash, redirect , request, Blueprint
from flask_login import login_user , current_user , logout_user , login_required

users = Blueprint('users',__name__)

@users.route("/sign-up",methods=['GET','POST'])
def sign_up():
    form = SignupForm()
    if(form.validate_on_submit()):
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        new_user = User(firstname = form.first_name.data , lastname = form.last_name.data,
                        email = form.email.data , password = hashed_password , 
                        birthday = form.birthday.data )
        new_user.add_user()
        flash(f"Welcome {form.first_name.data} {form.last_name.data} to Express!","success")
        return redirect(url_for('users.log_in'))
    return render_template("sign_up.html",form = form,title = "Sign Up")

@users.route("/log-in",methods=['GET','POST'])
def log_in():
    form = LoginForm()
    if(form.validate_on_submit()):
        user = User.query.filter_by(email=form.email.data).first()
        if(user and bcrypt.check_password_hash(user.password,form.password.data)):
            login_user(user,remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f"Welcome back to Express!","success")
            return  redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(f"Please check your email and password!","danger")

    return render_template("log_in.html",form = form,title = "Log In")

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account",methods=['GET','POST'])
@login_required
def account():
    image = url_for('static',filename='images/profile_pictures/'+ current_user.image_file)
    form = UpdateAccountForm()
    posts_published = Post.posts_published()
    if(form.validate_on_submit()):
        if(form.picture.data):
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.firstname = form.first_name.data
        current_user.lastname = form.last_name.data
        current_user.email = form.email.data
        current_user.birthday = form.birthday.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.first_name.data = current_user.firstname
        form.last_name.data = current_user.lastname
        form.email.data = current_user.email
        form.birthday.data = current_user.birthday

    return render_template("account.html",title = "Account",image = image,form = form, posts_published=posts_published)

@users.route("/user/<string:username>")
@login_required
def user_profile(username):
    image = url_for('static',filename='images/profile_pictures/'+ current_user.image_file)
    page = request.args.get('page',default = 1,type = int)
    user = User.query.filter_by(username = username).first_or_404()
    posts_published = Post.posts_published()
    posts = Post.query.filter_by(author = user)\
            .order_by(Post.date_posted.desc()).paginate(page=page,per_page = 5)
    return render_template('user_profile.html' , title=username, image = image, posts = posts , user =user, posts_published=posts_published)

@users.route("/reset_password",methods=['GET','POST'])
def reset_password_request():
    if(current_user.is_authenticated):
        return redirect(url_for('main.home'))
    form = ResetPasswordRequestForm()
    if(form.validate_on_submit()):
        user = User.query.filter_by(email = form.email.data).first()
        send_reset_password_email(user)
        flash('An email has been sent to reset your password','info')
        return redirect(url_for("users.log_in"))
    return render_template('reset_password_request.html' , title="Reset Password", form = form)

@users.route("/reset_password/<token>",methods=['GET','POST'])
def reset_password(token):
    if(current_user.is_authenticated):
        return redirect(url_for('main.home'))
    user = User.verify_token(token)
    if(user is None):
        flash("Something went wrong! Pleast try again.","danger")
        return redirect(url_for("users.reset_password_request"))
    form = ResetPasswordForm()
    if(form.validate_on_submit()):
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f"Your password has been updated! You are now able to login! ","success")
        return redirect(url_for('users.log_in'))

    return render_template('reset_password.html' , title="Reset Password", form = form)

express/templates/header.html
{% extends "layout.html" %}

<!-- Start HeadBlock -->
{% block headblock%}
<link rel="stylesheet" href="{{url_for('static',filename='styles/header_style.css')}}">

  {% block head_afterheader %}

  {% endblock head_afterheader%}

{% endblock headblock%}
<!-- End HeadBlock -->

<!-- Start BodyBlock -->
{% block bodyblock%}
<header class="mb-3 border-bottom">
    <div class="container d-grid gap-3 align-items-center" style="grid-template-columns: 1fr 2fr;">
        <a href="{{url_for('main.home')}}" class="d-flex align-items-center text-white text-decoration-none" style="width: 100px;">
            <img src="{{url_for('static',filename='images/logo.png')}}" alt="Express Logo" width="100px">
        </a>

      <div class="d-flex align-items-center">
        <form class="w-100 me-3" role="search" action="{{url_for('posts.search')}}">
          <input type="search" class="form-control" placeholder="Search..." aria-label="Search" name="query">
        </form>

        <div class="flex-shrink-0 dropdown">
          <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{{image}}" alt="mdo" width="32" height="32" class="rounded-circle">
          </a>
          <ul class="dropdown-menu text-small shadow">
            <li><a class="dropdown-item" href="{{url_for('posts.create_post')}}">New post...</a></li>
            <li><a class="dropdown-item" href="{{url_for('users.account')}}">Account</a></li>
            <li><a class="dropdown-item" href="{{url_for('users.user_profile',username = current_user.username)}}">Profile</a></li>
            <li><a href="mailto:mahrezbey@gmail.com?subject=[From%Express]" class="dropdown-item">Contact</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{{url_for('users.logout')}}">Logout</a></li>
          </ul>
        </div>
      </div>
    </div>
  </header>

{% block afterheader %}
{% endblock afterheader%}
{% endblock bodyblock%}
<!-- EndBodyBlock -->

express/templates/home.html
{% extends "header.html" %}


{% block head_afterheader %}
<link rel="stylesheet" href="{{url_for('static',filename='styles/home_style.css')}}">

{% endblock head_afterheader%}
<!-- Part After Header -->
{% block afterheader %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div id="content" class="content content-full-width">
                <!-- <div class="card mb-3"> -->
                    <div class="card-body pt-3 m-auto" style="width: fit-content;">
                        {% with messages = get_flashed_messages(with_categories=true) %}
                            {% if messages %}
                                {% for category, message in messages %}
                                    <div class="alert alert-{{ category }}">
                                    {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        {% endwith %}
                    </div>
                <!-- </div> -->
                <div class="profile-content">
                    <div class="tab-content">
                            <ul class="timeline">
                                {% for post in posts.items %}
                                <li>
                                    <div class="timeline-time">
                                        <span class="date">{{post.date_posted.strftime('%Y/%m/%d') }}</span>
                                        <span class="time">{{post.date_posted.strftime('%H:%M') }}</span>
                                    </div>
                                    <div class="timeline-icon">
                                        <span href="">&nbsp;</span>
                                    </div>
                                    <div class="timeline-body">
                                        <a class="timeline-header" href="{{url_for('users.user_profile',username = post.author.username)}}">
                                            <span class="userimage rounded-circle "><img src="{{url_for('static',filename='images/profile_pictures/'+post.author.image_file)}}" alt="user image"></span>
                                            <span class="username">{{post.author.firstname}} {{post.author.lastname}}</span>
                                        </a>
                                        <div class="timeline-content my-4">
                                            <h4 class="template-title fw-bold" style="color: var(--main-light-color); text-decoration: underline;">
                                                {{post.title}}
                                            </h4>
                                            <br>
                                            <p>{{post.content}}</p>
                                        </div>
                                        <div class="timeline-footer">
                                            {% if current_user == post.author %}
                                                <a type="button" class="btn text-primary" href="{{url_for('posts.edit_post',post_id = post.id)}}" ><i class="fa fa-edit fa-fw fa-lg "></i> Edit</a> 
                                                <button type="button" class="btn text-danger" data-bs-toggle="modal" data-bs-target="#deleteModal" ><i class="fa fa-trash fa-fw fa-lg "></i> Delete </button>
                                            {% endif%}
                                        </div>

                                        <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Post</h1>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        Are you sure you want to delete this post?
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                        <a type="button" class="btn btn-danger" href="{{url_for('posts.delete_post',post_id = post.id)}}">Delete</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <!-- end timeline-body -->
                                </li>
                                {% endfor %}
                            </ul>
                    </div>
                    {% if context == "Home" %}
                    <nav aria-label="Page navigation example my-5" class="d-flex justify-content-center mt-5 mb-3 posts-pagination">
                        <ul class="pagination">
                            {% if posts.page >1 %}
                                <li class="page-item">
                                    <a class="page-link" href="{{url_for('main.home', page=posts.page-1)}}" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                            {% endif%}
                            {% for page_number in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                                {% if page_number %}
                                    {% if page_number == posts.page %}
                                        <li class="page-item active "><a class="page-link" href="{{url_for('main.home', page=page_number)}}">{{page_number}}</a></li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link" href="{{url_for('main.home', page=page_number)}}">{{page_number}}</a></li>
                                    {% endif%}    
                                {% else %}
                                    <span class="d-inline-block mx-2">...</span>
                                {% endif%}
                            {% endfor%}
                            {% if posts.page < posts.pages %}
                            <li class="page-item">
                                <a class="page-link" href="{{url_for('main.home', page=posts.page+1)}}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                            {% endif%}
                        </ul>
                    </nav>
                    {%else%}
                    <nav aria-label="Page navigation example my-5" class="d-flex justify-content-center mt-5 mb-3 posts-pagination">
                        <ul class="pagination">
                            {% if posts.page >1 %}
                                <li class="page-item">
                                    <a class="page-link" href="{{url_for('posts.search', page=posts.page-1, query=request.args.get('query'))}}" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                            {% endif%}
                            {% for page_number in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                                {% if page_number %}
                                    {% if page_number == posts.page %}
                                        <li class="page-item active "><a class="page-link" href="{{url_for('posts.search', page=page_number, query=request.args.get('query'))}}">{{page_number}}</a></li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link" href="{{url_for('posts.search', page=page_number, query=request.args.get('query'))}}">{{page_number}}</a></li>
                                    {% endif%}    
                                {% else %}
                                    <span class="d-inline-block mx-2">...</span>
                                {% endif%}
                            {% endfor%}
                            {% if posts.page < posts.pages %}
                            <li class="page-item">
                                <a class="page-link" href="{{url_for('posts.search', page=posts.page+1, query=request.args.get('query'))}}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                            {% endif%}
                        </ul>
                    </nav>
                    {% endif%}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock afterheader%}
<!-- Part After Header -->

express/templates/log_in.html
{% extends "layout.html"%}
<!-- Start HeadBlock -->
    {% block headblock%}
    <link rel="stylesheet" href="{{url_for('static',filename='styles/log_in_style.css')}}">
    {% endblock headblock%}
<!-- End HeadBlock -->

<!---------------------------------------- Start Body  --------------------------------------------------------->
{% block bodyblock %}
<div class="log-in-page container-fluid vh-100 d-flex align-items-center justify-content-center">
    <div class="container" style="width: 700px;max-height: 80vh;overflow-y: auto;">
        <div class="logo-page position-absolute top-0 start-0">
            <a href="{{url_for('main.home')}}"><img src="{{url_for('static',filename='images/logo.png')}}" alt="logo" width="75"></a>
        </div>
        <div class="row">
            <div class="col px-5 py-2">
                <div class="fs-1 mb-5 heading">Login</div>
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                            {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                <form action="" method="post" novalidate>
                    {{ form.hidden_tag() }}

                    <div class="row mt-3 flex-column flex-md-row">
                        <div class="col">
                            {{form.email.label}}
                        </div>
                        <div class="col">
                            {% if form.email.errors %}
                                {{form.email(placeholder="Enter your email",class="form-control is-invalid")}}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{form.email(placeholder="Enter your email",class="form-control")}}
                            {% endif %}
                        </div>
                    </div>
    
                    <div class="row mt-3 flex-column flex-md-row">
                        <div class="col">
                            {{ form.password.label }}
                        </div>
                        <div class="col">
                            {% if form.password.errors %}
                                {{form.password(placeholder="Enter your password",class="form-control is-invalid")}}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{form.password(placeholder="Enter your password",class="form-control")}}
                            {% endif %}
                        </div>
                    </div>
                    
                    <div class="remember-me" style="margin:20px 0 20px 10px;">
                        {{form.remember(class="form-check-input",style="margin: 0 10px 0 -10px")}}
                        {{form.remember.label(class="form-check-label") }}
                    </div>
    
                    {{form.submit(class="btn submit-button")}}
                    <span class="to-sign" style="margin-top: 20px;">Forget Your Password? <a href="{{url_for('users.reset_password_request')}}">Reset</a> </span>
                    <span class="to-sign" style="margin-top: 20px;">Don't Have An Account? <a href="{{url_for('users.sign_up')}}">Sign Up</a> </span>
    
                </form>
            </div>
        </div>

    </div>
</div>

{% endblock bodyblock %}
<!------------------------------------------- End Body  -------------------------------------------------------->

express/templates/reset_password_request.html
{% extends "layout.html"%}
<!-- Start HeadBlock -->
    {% block headblock%}
    <link rel="stylesheet" href="{{url_for('static',filename='styles/log_in_style.css')}}">
    {% endblock headblock%}
<!-- End HeadBlock -->

<!---------------------------------------- Start Body  --------------------------------------------------------->
{% block bodyblock %}
<div class="log-in-page container-fluid vh-100 d-flex align-items-center justify-content-center">
    <div class="container" style="width: 700px;max-height: 80vh;overflow-y: auto;">
        <div class="logo-page position-absolute top-0 start-0">
            <a href="{{url_for('main.home')}}"><img src="{{url_for('static',filename='images/logo.png')}}" alt="logo" width="75"></a>
        </div>
        <div class="row">
            <div class="col px-5 py-2">
                <div class="fs-1 mb-5 heading">Reset Password</div>
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                            {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                <form action="" method="post" novalidate>
                    {{ form.hidden_tag() }}

                    <div class="row mt-3 flex-column flex-md-row">
                        <div class="col">
                            {{form.email.label}}
                        </div>
                        <div class="col">
                            {% if form.email.errors %}
                                {{form.email(placeholder="Enter your email",class="form-control is-invalid")}}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{form.email(placeholder="Enter your email",class="form-control")}}
                            {% endif %}
                        </div>
                    </div>
    
                    {{form.submit(class="btn submit-button mt-5")}}
    
                    <span class="to-sign" style="margin-top: 20px;">Don't Have An Account? <a href="{{url_for('users.sign_up')}}">Sign Up</a> </span>
                </form>
            </div>
        </div>

    </div>
</div>

{% endblock bodyblock %}
<!------------------------------------------- End Body  -------------------------------------------------------->

express/templates/welcome_page.html
{% extends 'layout.html' %}

<!-- Start HeadBlock -->
{% block headblock%}
<link rel="stylesheet" href="{{url_for('static',filename='styles/welcome_page_style.css')}}">
{% endblock headblock%}
<!-- End HeadBlock -->
{% block bodyblock%}

<!-- Start BodyBlock -->
<div class="welcome-page">
    <header class="p-3">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="{{url_for('main.home')}}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <img src="{{url_for('static',filename='images/logo.png')}}" alt="Express Logo" width="120px">
                </a>
    
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{{url_for('main.home')}}" class="nav-link px-2 fs-5 fw-bold  text-white active">Home</a></li>
                    <li><a href="mailto:mahrezbey@gmail.com?subject=[From%Express]" class="nav-link px-4 fs-5 fw-bold text-white">Contact</a></li>
                </ul>
        
                <div class="text-end">
                    <a type="button" href="{{url_for('users.log_in')}}" class="btn btn-outline-light me-2 fs-5 fw-bold">Login</a>
                    <a type="button" href="{{url_for('users.sign_up')}}" class="btn fs-5 fw-bold">Sign-up</a>
                </div>
            </div>
        </div>
    </header>

    <div class=" welcome-page-content container col-xxl-8 px-4">
        <div class="row flex-lg-row-reverse align-items-center justify-content-center g-5 ">
            <div class="col-10 col-sm-8 col-lg-6">
                <img src="{{url_for('static',filename='images/welcome-icon.png')}}" class="d-block mx-lg-auto img-fluid" alt="Welcome Icon" width="450" height="450" loading="lazy">
            </div>
            <div class="col-lg-6">
                <h1 class="display-5 fw-bold lh-1 mb-3 text-white">Where you can Express to Impress!</h1>
                <p class="lead text-white py-5 lh-lg">Express is the best platform to to create and share your thoughts, ideas, interests about movies and tv-shows to the world.</p>
                <div class="d-grid gap-2 d-md-flex justify-content-center">
                    <a href="{{url_for('users.sign_up')}}" type="button" class="btn btn-lg px-4 me-md-2 mb-3 mb-lg-0 text-white">Sign Up Today In Express</a>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock bodyblock%}
<!-- EndBodyBlock -->